### ISSUE TITLE
Reboot instead of power off

### ISSUE THREAD

**Issue by ste310** [NovaFusion/android_device_samsung_golden#21]
Hi,
thank you very much for your work!
I hope i'm writing on the correct section. I installed Cyanogenmod 11 on my S3 Mini.
It works fine! Congratulations!

Anyway, i found out a little issue:
if i connect the phone (turned on) to the battery charger and then i turn it off, the phone doesn't power off, but reboots.
So, i have to disconnect the battery charger cable, power off, and then reconnect the battery charger.

Let me know if someone have experienced something like that.

Thanks

**Comment by exic** [comment]
I've head this behavior as well.

**Comment by jaysn** [comment]
i think there may be e problem with init.rc, i dont know enough about the android init process but could it be that the charger mode after the shutdown triggers the "re"boot? or maybe (if not using on charger, that could be the problem) the missing on charger to stop the init process is the problem? as said initially, i dont know enough about the android init process nor do i know enough about this roms sources :S

**Comment by Piero512** [comment]
Maybe it's because of a workaround used for the USB OTG charging bug
