### ISSUE TITLE
Weird bug on CM Perfomance menu

### ISSUE THREAD

**Issue by Piero512** [NovaFusion/android_device_samsung_golden#22]
When I enter the perfomance menu, and do something (like scrolling down the notification bar), the processor min speed sets itself at 1000Mhz and when i return to the menu, it sets back to 200mhz. Using some CPU tuner apps i see that when i leave that menu, it happens to be set on 1000Mhz.
![image](https://cloud.githubusercontent.com/assets/6634316/3870401/15a25854-20cc-11e4-99af-2e1f95af6312.png)
![image](https://cloud.githubusercontent.com/assets/6634316/3870403/447bae5a-20cc-11e4-9648-8ee8e5b8d958.png)

**Comment by m-chojnacki** [comment]
It's not a bug, it's a feature.
CPU frequency boosts after you touch the screen to ensure the scrolling would be smooth.

**Comment by Piero512** [comment]
But  Project Butter just boost the frequency of the CPU and not the minimum cpu freq. I haven't moved any of the controls there.

First of all is the Current CPU freq. Looking forward to reproduce this with a video.
EDIT: http://youtu.be/qYluyOZNYOA

**Comment by m-chojnacki** [comment]
Butter on U8500 boosts minimum cpu freq, not current. Effect is the same.
