### ISSUE TITLE
Phone turns off when full charged

### ISSUE THREAD

**Issue by chemstar** [NovaFusion/android_device_samsung_golden#35]
hi, maybe is an issue or battery problem but everytime i charge (full) the phone i find it powered off.
i've changed my battery last monts and have done full reset before installing the last rom.

**Comment by chemstar** [comment]
i did bought another battery and all fine now

**Comment by thesneaker** [comment]
Hi @chemstar and @maclaw ,
why was this bug closed? Did the problem go away for you?
I observed the the same behaviour with a recent stable release [cm12.1_golden.nova.20160210.ODIN_TWRP]. I didn't find anything about that in the changelogs of the following monthly releases, so I'm guessing this really annoying bug isn't fixed.

I installed the mentioned release cleanly as per your guide with an original Samsung battery which was about 1 year in use. The bugs reproduceability is about 50%, which is still about every other day! To rule out a faulty battery I bought a decent quality replacement from Anker. But the bug persists.

If you need certain logs or something just tell me.
