### ISSUE TITLE
MTP over USB not working on I8190

### ISSUE THREAD

**Issue by jankantert** [NovaFusion/android_device_samsung_golden#38]
In CM12 (Build 12-2015311-UNOFFICIAL-golden) MTP is not working properly. When I connect the phone to my PC (tried Ubuntu 14.04 and Windows 7) the device will not show any data partitions. Adb is also not working fully, so this may be also USB related:

``` bash
$ adb devices 
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached 
xxxxxxxxxxxxxx  offline
```

Additionally, when I open Settings -> Storage -> USB Connection and click on PTP or MTP the settings dialog crashes.

**Comment by antonh1611** [comment]
Same here but with Mint 16.
and sometimes in adb devices it say unauthorized, but no confirmation dialog!
adb over wifi not working either, so i guess it is not an usb driver problem.
adb can connect but not authorized over wifi!

**Comment by jankantert** [comment]
Still no luck with build 12-20150205-UNOFFICIAL-golden

**Comment by antonh1611** [comment]
here is the logcat when settings crash on changing usb connection, but i cannot see anything useful:

--------- beginning of main
D/OpenGLRenderer( 5832): Render dirty regions requested: false
D/Atlas   ( 5832): Validating map...
D/libEGL  ( 5832): loaded /system/lib/egl/libEGL_mali.so
D/libEGL  ( 5832): loaded /system/lib/egl/libGLESv1_CM_mali.so
D/libEGL  ( 5832): loaded /system/lib/egl/libGLESv2_mali.so
I/OpenGLRenderer( 5832): Initialized EGL, version 1.4
D/OpenGLRenderer( 5832): Enabling debug mode 0
D/Terminal( 5832): Bound to service with 0 active terminals
D/Terminal( 5832): entering read() loop
D/Terminal( 5832): setColors(0xffffffff, 0xff000000)
D/Terminal( 5832): resize(18, 30, 100)
I/Timeline( 5832): Timeline: Activity_idle id: android.os.BinderProxy@118386de time:729178
D/Terminal( 5832): resize(9, 30, 100)
D/TerminalKeys( 5832): dispatched key event: mod=0, character='l'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='o'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='g'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='c'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='a'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='t'
D/TerminalKeys( 5832): dispatched key event: mod=0, keys=VTERM_KEY_ENTER
W/IInputConnectionWrapper( 5832): showStatusIcon on inactive InputConnection
D/Terminal( 5832): setColors(0xffffffff, 0xff000000)
D/Terminal( 5832): Bound to service with 1 active terminals
I/Timeline( 5832): Timeline: Activity_idle id: android.os.BinderProxy@118386de time:760324
D/Terminal( 5832): resize(18, 30, 100)
D/Terminal( 5832): resize(9, 30, 100)
D/Terminal( 5832): resize(18, 30, 100)
D/Terminal( 5832): resize(9, 30, 100)
D/Terminal( 5832): resize(18, 30, 100)
W/InputEventReceiver( 5832): Attempted to finish an input event but the input event receiver has already been disposed.
D/Terminal( 5832): kill() requested
D/Terminal( 5832): entering read() loop
D/Terminal( 5832): setColors(0xffffffff, 0xff000000)
D/Terminal( 5832): resize(18, 30, 100)
W/IInputConnectionWrapper( 5832): showStatusIcon on inactive InputConnection
D/Terminal( 5832): setColors(0xffffffff, 0xff000000)
D/Terminal( 5832): Bound to service with 1 active terminals
I/Timeline( 5832): Timeline: Activity_idle id: android.os.BinderProxy@118386de time:822588
D/Terminal( 5832): resize(9, 30, 100)
D/TerminalKeys( 5832): dispatched key event: mod=0, character='l'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='o'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='g'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='c'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='a'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='t'
D/TerminalKeys( 5832): dispatched key event: mod=0, keys=VTERM_KEY_ENTER
D/Terminal( 5832): resize(18, 30, 100)
W/IInputConnectionWrapper( 5832): showStatusIcon on inactive InputConnection
D/Terminal( 5832): Bound to service with 1 active terminals
D/Terminal( 5832): setColors(0xffffffff, 0xff000000)
I/Timeline( 5832): Timeline: Activity_idle id: android.os.BinderProxy@396a5825 time:871996
D/Terminal( 5832): resize(9, 30, 100)
W/InputEventReceiver( 5832): Attempted to finish an input event but the input event receiver has already been disposed.
D/Terminal( 5832): kill() requested
I/OpenGLRenderer( 5832): Initialized EGL, version 1.4
D/Terminal( 5832): Bound to service with 0 active terminals
D/Terminal( 5832): entering read() loop
D/Terminal( 5832): setColors(0xffffffff, 0xff000000)
D/Terminal( 5832): resize(18, 30, 100)
I/Timeline( 5832): Timeline: Activity_idle id: android.os.BinderProxy@396a5825 time:934437
D/Terminal( 5832): resize(9, 30, 100)
D/TerminalKeys( 5832): dispatched key event: mod=0, character='l'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='o'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='g'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='c'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='a'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='t'
D/TerminalKeys( 5832): dispatched key event: mod=0, character=' '
D/TerminalKeys( 5832): dispatched key event: mod=1, character='>'
D/TerminalKeys( 5832): dispatched key event: mod=0, character=' '
D/TerminalKeys( 5832): dispatched key event: mod=0, character='/'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='s'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='d'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='c'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='a'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='r'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='d'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='/'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='l'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='p'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='g'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='c'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='a'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='t'
D/TerminalKeys( 5832): dispatched key event: mod=0, keys=VTERM_KEY_BACKSPACE
D/TerminalKeys( 5832): dispatched key event: mod=0, keys=VTERM_KEY_BACKSPACE
D/TerminalKeys( 5832): dispatched key event: mod=0, keys=VTERM_KEY_BACKSPACE
D/TerminalKeys( 5832): dispatched key event: mod=0, keys=VTERM_KEY_BACKSPACE
D/TerminalKeys( 5832): dispatched key event: mod=0, keys=VTERM_KEY_BACKSPACE
D/TerminalKeys( 5832): dispatched key event: mod=0, character='o'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='g'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='c'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='a'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='t'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='.'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='t'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='x'
D/TerminalKeys( 5832): dispatched key event: mod=0, character='t'
D/TerminalKeys( 5832): dispatched key event: mod=0, keys=VTERM_KEY_ENTER
W/IInputConnectionWrapper( 5832): showStatusIcon on inactive InputConnection
D/Terminal( 5832): setColors(0xffffffff, 0xff000000)
D/Terminal( 5832): Bound to service with 1 active terminals
I/Timeline( 5832): Timeline: Activity_idle id: android.os.BinderProxy@396a5825 time:1003575
D/Terminal( 5832): resize(18, 30, 100)
D/Terminal( 5832): resize(9, 30, 100)

**Comment by jankantert** [comment]
Fixed in current release (build 12-20150209-UNOFFICIAL-golden). Thanks!

**Comment by valduze** [comment]
Where can I get the source of this ROM so that I can compile it my self and fix the incoming call  crashing problem or please fix it

**Comment by jankantert** [comment]
No related to bug. But I would start here: https://github.com/NovaFusion/android_device_samsung_golden/tree/cm-12.0. Fork and create a Pull Request when succeeded.
