### ISSUE TITLE
[CM11] Auto-Brightness not working on S3 mini I8190

### ISSUE THREAD

**Issue by suuuehgi** [NovaFusion/android_device_samsung_golden#43]
Hey,

I hope I'm right here since I can't find something called "bugtracker" on the novafusion page and there are no links to it.

Well, I'm using a Samsung Galaxy S3 mini I8190 with CM11 and the auto-brightness function is not working. When I press the "Auto" button, the settings button on the right appears and immediately disappears again. So the auto-brightness is completely out of work.

Thanks a lot for any help!

P.s.: The twilight app is not working as well -- I think this is related to this issue. The preview works fine but the deamon doesn't change any color.

**Comment by PedroMCostaAndrade** [comment]
Se dont havê this sensor so it's normal that doesn't work ;)
The problem with the APP is something completely different

**Comment by PedroMCostaAndrade** [comment]
We don't***

**Comment by suuuehgi** [comment]
Oh, really -- I'm really starting to dislike this phone. Thank you and I'm sorry for the wrong issue.
Solved it using this [workaround](http://forum.xda-developers.com/showthread.php?t=2324762).
